### ISSUE TITLE
Add an option for GitLab login

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1013]
## Context

Currently, we allow users to Sign up/Sign in with GitHub. 
We would like to offer the option to sign in using GitLab.

## Expected Behavior

The Codú project uses [Next Auth](https://next-auth.js.org/) as its open source authentication library.

Docs for the [GitLab provider](https://next-auth.js.org/providers/gitlab#options)

## Screenshots

![Current login screen](https://github.com/user-attachments/assets/aab7ba8e-4985-490a-a2e2-81c83b3fdf4f)

## Additional info

You can follow the pattern on the GitHubProvider which you can find at 
>server>auth.ts

Any questions, feel free to ask.

**Comment by John-Paul-Larkin** [comment]
@NiallJoeMaher 

When this is implemented we need to add a section in the readme for GitLab env variables.

**Comment by sleithdylan** [comment]
@NiallJoeMaher @John-Paul-Larkin 

I'll take this one.

quick question, for the button do you want it the same style and everything (with the text and icon changed to GitLab's) but in a column (so just below the GitHub login) or would you like the GitHub and GitLab in 2 columns?

I think it would look better in a column to just fill up some space because the login page feels a bit empty since there are no email/password inputs.

Also, if you would like me to along with this PR, I can update the README too. 😄

**Comment by John-Paul-Larkin** [comment]
Awesome, thanks Dylan.
I would agree that column would look best. 
As for the styling, I think you can copy the styles initially and just focus on wiring up the logic. It will be easy to change them in the future. Im sure @NiallJoeMaher will have an idea for the styles anyway.

**Comment by sleithdylan** [comment]
Okay cool, no problem I will do that so. 😄
