### ISSUE TITLE
Show copy code block icon only on hover

### ISSUE THREAD

**Issue by praveen-quizizz** [codu-code/codu#344]
## Expected Behavior

The copy icon should be displayed when the user hovers over the code block.

## Current Behavior

Currently the icon is always visible leading to poor reading experience.

## Screenshots

![image](https://github.com/codu-code/codu/assets/98312397/01a4dc86-8a13-4a6a-967f-85ff408c62b6)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Goto any article with code block e.g. https://www.codu.co/articles/setting-up-metacall-development-environment-on-windows-jxk6iltl

**Comment by Shane-Donlon** [comment]
Hi Praveen,

Requirements update:

1. The copy / clipboard button should be visible for mobile.
2. The code excerpt / text should be completely visible to reduce side-scrolling.
3. On desktop the copy / clipboard button should be visible on mouse hover.


Thanks,
Shane

**Comment by sudarshansb143** [comment]
@NiallJoeMaher Suggested enhancement here. Is the underlined empty space on code block is is needed or we can make `copy code` button positioning `absolute` so that it will remove this empty space ?
![image](https://github.com/codu-code/codu/assets/43947282/887b15de-eda4-4231-b76b-0603890c8c75)

Ex. 
![image](https://github.com/codu-code/codu/assets/43947282/a5a3ec81-2e4c-46aa-9121-8b9b8a296360)

**Comment by NiallJoeMaher** [comment]
Thanks for that @sudarshansb143! We did that. 🥳
