### ISSUE TITLE
E2E Testing

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#468]
## Context

Right now, we have no e2e testing but Playwright setup.
We should have end-to-end testing enabled to make sure people are more comfortable changing things without fear of breaking things. 

The first thing would be some input on the appropriate testing.

Then, once we have decided on some appropriate areas, we can split the testing into issues to share the workload. 

## Expected Behavior

Test all major functionality for the application in e2e tests. 

## Current Behavior

No testing 😢

**Comment by JohnAllenTech** [comment]
Working on this one over the weekend @NiallJoeMaher @John-Paul-Larkin 

Any particular tests you would like to see added?

I have the GH auth flow working in playwright so we can test authenticated portions of the application now like Creating a post, commenting on a post etc

**Comment by John-Paul-Larkin** [comment]
Hey @JohnAllenTech 

I have not done any testing, so I am eager to learn. I was reluctant to make issues until I have a better understanding myself.

> Any particular tests you would like to see added?

Long term, we should cover as much as possible, but for now the plan is to break this up in to specific issue.
Auth flow is a great start, and since @sleithdylan recently added GitLab login, we should also add tests for that. 

- Tests for the main forms, which are the user settings page and the onboarding form.
- Tests for the alpha editor, which will replace the current editor shortly.
- Navigation tests between the key pages.
- Search functionality tests

Im really just guessing here, but I can look into it properly later and we can make a proper plan on Mondays livestream? @NiallJoeMaher

**Comment by NiallJoeMaher** [comment]
Yes @JohnAllenTech. We can make a heap of issues from this so we can get contributors helping out too. 
- Confirm all the pages work as expected with/without auth.
- Confirm all links work (mobile/desktop) with/without auth.
- Confirm features like comments, likes, bookmarks, creating posts etc.
But yeah, it's basically test the f*ck out of everything!
