### ISSUE TITLE
Feature: Schedule articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#689]
## Context

I think it would be useful if we could schedule articles so that I can batch create articles and schedule them for regular intervals

## Expected Behavior

User can schedule articles to be released in the future.
I will look for patterns on doing this but my initial feeling is that if we add a published date in the future we should be able to just hide all posts until the published time has hit since currently we use a timestamp at publish time. 

## Current Behavior

The options are to save and publish. There is no schedule option.

**Comment by sonngdev** [comment]
This one is interesting and I would love to learn more about how it can be implemented. Looking into this.

**Comment by sonngdev** [comment]
There are two approaches to this feature:
1. Use a separate task queue to schedule and publish posts at the desired time. Common solutions include [Bull](https://github.com/OptimalBits/bull) (for Node.js) and [Quirrel](https://quirrel.dev/) (specifically for Next.js). This approach complicates the architecture and deployment, because we need to maintain an additional queue.
2. We can achieve the same thing by using the field `published` in the table `Post` which is already there. When users choose to schedule a post, add it to the DB but set its `published` time to another point in the future. The sites should be made to only show posts with `published <= now`.

For now the second approach makes more sense to me. Let me know if I miss anything.

**Comment by NiallJoeMaher** [comment]
@thanhsonng I was thinking of option 2 myself! Seems like the easiest considering the current setup. Then we can just alter the API to get articles to have the new constraints

**Comment by sonngdev** [comment]
@NiallJoeMaher Yes I definitely followed your pointer there and came to the same conclusion. I can try implementing this and submit a PR soon, should be super helpful for someone who publishes a lot like you.
