### ISSUE TITLE
Accessibility improvement opportunities 

### ISSUE THREAD

**Issue by Shane-Donlon** [codu-code/codu#745]
## Context

Please provide any relevant information about your setup:
[Page Speed Insights results](https://pagespeed.web.dev/analysis/https-www-codu-co/gp8g9869c6?form_factor=desktop)

Feedback:

- Buttons do not have an accessible name
 
- Background and foreground colors do not have a sufficient contrast ratio.
 

## Screenshots

![Google Lighthouse report error for poor contrast ratio in search bar](https://github.com/codu-code/codu/assets/130906067/d41ff27e-302c-4ecd-b79f-0f3b9ce9cb6f)
![Google Lighthouse report error for button does not have an accessible name](https://github.com/codu-code/codu/assets/130906067/8b3da656-937b-4d04-84a5-fcbd6de83d04)

**Comment by Maczi01** [comment]
I think I can take it, but it require design changes. Should I focus only on contrast, ore something else? Or wait for storybook (a11y tests can be done there)

**Comment by NiallJoeMaher** [comment]
@Maczi01 - I'm looking into this! I have some new designs. I also want to see how Storybook works with severside components. I know they recently started supporting this, and that's the way we are heading. The new designs will hopefully get rid of some of these issues. 

Some of these things don't need to be fixed (like the CMD+K text) because it's just a placeholder and they can often fail here. 

The button to scroll down definitely could use an accessible name, though, if you want to take that?

**Comment by Maczi01** [comment]
Thanks for quick answer @NiallJoeMaher !

I heard they added support for RSC, but didn't try yet. No rush! If you need, I can try to help with it. 

I can handle scroll issue, assign to me pls :-)
