### ISSUE TITLE
Recent bookmarks - auto update UI and update feedback

### ISSUE THREAD

**Issue by Shane-Donlon** [codu-code/codu#834]
## Expected Behavior

Please describe the behavior you are expecting

- When I click on the bookmark icon the "recent bookmarks" should auto add or remove the bookmark without having to refresh the page.

- When adding or removing a bookmarked article if the action is unsuccessful there should be a toast notification with simple actions to resolve.

## Current Behavior

What is the current behavior?

When I click on the bookmark icon in an article, the icon will change colour (provides feedback), 
but I need to manually refresh the page to see the updated bookmarks,

**Comment by revanthnetha** [comment]
Is this issue up-for-grab. Could you assign this to me @John-Paul-Larkin @Shane-Donlon

**Comment by John-Paul-Larkin** [comment]
It certainly is @revanthnetha.
I assigned you.

**Comment by John-Paul-Larkin** [comment]
@revanthnetha 
I just looked at the SideBarSavedPosts function which displays the recent bookmarks.
As part of this PR can you handle the included TODO
  // @TODO query the backend to get the last 3 instead of slice

You can modify your tRPC query to return only the latest three posts directly from the backend, instead of fetching all and slicing them on the front end.

Thanks

**Comment by revanthnetha** [comment]
Could you check the PR @John-Paul-Larkin . Happy to do Changes if needed :)
